/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
content: [
  "./resources/views/**/*.blade.php",
  "./resources/js/**/*.js",
],
// safelist: [
//   {
//     // pattern: /.*/,
//   },
// ],
  theme: {
    extend: {
      colors: {
        
                         "primary-fixed": "#d0e4ff",
                         "on-tertiary-container": "#585f00",
                         "on-primary-fixed": "#001d35",
                         "on-error": "#ffffff",
                         "surface": "#f8f9fa",
                         "surface-variant": "#e1e3e4",
                         "error": "#ba1a1a",
                         "inverse-surface": "#2e3132",
                         "outline-variant": "#c3c7cf",
                         "on-secondary-container": "#646465",
                         "background": "#f8f9fa",
                         "primary": "#3e6185",
                         "surface-container-lowest": "#ffffff",
                         "inverse-on-surface": "#f0f1f2",
                         "tertiary-fixed-dim": "#c3d000",
                         "on-tertiary": "#ffffff",
                         "primary-fixed-dim": "#4edea3",
                         "outline": "#73777f",
                         "surface-container": "#edeeef",
                         "on-surface-variant": "#42474e",
                         "surface-container-low": "#f3f4f5",
                         "on-secondary-fixed": "#1b1c1d",
                         "error-container": "#ffdad6",
                         "on-primary": "#ffffff",
                         "on-tertiary-fixed": "#1b1d00",
                         "tertiary": "#5d6300",
                         "secondary-fixed-dim": "#c7c6c7",
                         "secondary": "#5e5e5f",
                         "surface-dim": "#d9dadb",
                         "tertiary-fixed": "#dfed1a",
                         "on-surface": "#191c1d",
                         "on-primary-container": "#395c80",
                         "on-secondary-fixed-variant": "#464748",
                         "secondary-container": "#e3e2e3",
                         "on-secondary": "#ffffff",
                         "secondary-fixed": "#e3e2e3",
                         "surface-tint": "#3e6185",
                         "surface-container-highest": "#e1e3e4",
                         "surface-bright": "#f8f9fa",
                         "on-primary-fixed-variant": "#25496c",
                         "on-tertiary-fixed-variant": "#454a00",
                         "primary-container": "#b2d5ff",
                         "success-container": "#55e01e",
                         "tertiary-container": "#cfdc00",
                         "on-error-container": "#93000a",
                         "on-background": "#191c1d",
                         "surface-container-high": "#e7e8e9",
                         "inverse-primary": "#a7caf3"
       },
      borderRadius: {
                         "DEFAULT": "0.25rem",
                         "lg": "0.5rem",
                         "xl": "0.75rem",
                         "full": "9999px" /* paste */ },
      spacing: {
                         "margin": "2rem",
                         "2xl": "4rem",
                         "base": "4px",
                         "xs": "0.25rem",
                         "sm": "0.5rem",
                         "md": "1rem",
                         "gutter": "1.5rem",
                         "lg": "1.5rem",
                         "xl": "2.5rem" /* paste */ },
      fontFamily: {
                         "h1": ["inter"],
                         "label-caps": ["manrope"],
                         "body-sm": ["inter"],
                         "h2": ["inter"],
                         "body-md": ["inter"],
                         "body-lg": ["inter"],
                         "display": ["inter"],
                         "mono": ["inter"] /* paste */ },
      fontSize: {
                         "h1": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                         "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
                         "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                         "h2": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                         "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                         "body-lg": ["18px", {"lineHeight": "1.5", "fontWeight": "400"}],
                         "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
                         "mono": ["13px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "400"}] /* paste */ },
    },
  },

  plugins: [
    // require("@tailwindcss/forms"),
    // require("@tailwindcss/container-queries"),
  ],
};