<?php

namespace App\Enums\Gensen;

enum ExportImportJobKey: string
{
    // EXPORT
    case EXPORT_LIST_DATA_BELUM_LENGKAP = 'EXPORT_LIST_DATA_BELUM_LENGKAP';
    case EXPORT_LIST_DATA_SIAP_VERIFIKASI = 'EXPORT_LIST_DATA_SIAP_VERIFIKASI';
    case EXPORT_LIST_DATA_VERIFIED = 'EXPORT_LIST_DATA_VERIFIED';
    case EXPORT_LIST_DATA_NO_INPUT_JAPAN = 'EXPORT_LIST_DATA_NO_INPUT_JAPAN';
    case EXPORT_LIST_DATA_DALAM_PENGAJUAN = 'EXPORT_LIST_DATA_DALAM_PENGAJUAN';

        // IMPORT
    case IMPORT_LIST_DATA_LENGKAP = 'IMPORT_LIST_DATA_LENGKAP';
    case IMPORT_LIST_DATA_VERIFIED = 'IMPORT_LIST_DATA_VERIFIED';
    case IMPORT_LIST_DATA_NO_INPUT_JAPAN = 'IMPORT_LIST_DATA_NO_INPUT_JAPAN';
    case IMPORT_LIST_DATA_DALAM_PENGAJUAN = 'IMPORT_LIST_DATA_DALAM_PENGAJUAN';
    case IMPORT_LIST_DATA_GENSEN_CAIR = 'IMPORT_LIST_DATA_GENSEN_CAIR';

    public function label(): string
    {
        return match ($this) {
            // EXPORT
            self::EXPORT_LIST_DATA_BELUM_LENGKAP => 'EXPORT LIST DATA BELUM LENGKAP',
            self::EXPORT_LIST_DATA_SIAP_VERIFIKASI => 'EXPORT LIST DATA SIAP VERIFIKASI',
            self::EXPORT_LIST_DATA_VERIFIED => 'EXPORT LIST DATA VERIFIED',
            self::EXPORT_LIST_DATA_NO_INPUT_JAPAN => 'EXPORT LIST DATA NO INPUT JAPAN',
            self::EXPORT_LIST_DATA_DALAM_PENGAJUAN => 'EXPORT LIST DATA DALAM PENGAJUAN',

            // IMPORT
            self::IMPORT_LIST_DATA_LENGKAP => 'IMPORT LIST DATA LENGKAP',
            self::IMPORT_LIST_DATA_VERIFIED => 'IMPORT LIST DATA VERIFIED',
            self::IMPORT_LIST_DATA_NO_INPUT_JAPAN => 'IMPORT LIST DATA NO INPUT JAPAN',
            self::IMPORT_LIST_DATA_DALAM_PENGAJUAN => 'IMPORT LIST DATA DALAM PENGAJUAN',
            self::IMPORT_LIST_DATA_GENSEN_CAIR => 'IMPORT LIST DATA GENSEN CAIR',
        };
    }
}
