<?php

namespace App\Enums\Gensen;

enum ExportImportJobKey: string
{
    // EXPORT
    case EXPORT_LIST_DATA_BELUM_LENGKAP = 'EXPORT_LIST_DATA_BELUM_LENGKAP';
    case EXPORT_LIST_DATA_SIAP_VERIFIKASI = 'EXPORT_LIST_DATA_SIAP_VERIFIKASI';
    case EXPORT_LIST_DATA_VERIFIED = 'EXPORT_LIST_DATA_VERIFIED';
    case EXPORT_LIST_DATA_NO_INPUT_JAPAN = 'EXPORT_LIST_DATA_NO_INPUT_JAPAN';
    case EXPORT_LIST_DATA_DALAM_PENGAJUAN = 'EXPORT_LIST_DATA_DALAM_PENGAJUAN';

        // IMPORT
    case IMPORT_LIST_DATA_LENGKAP = 'IMPORT_LIST_DATA_LENGKAP';
    case IMPORT_LIST_DATA_VERIFIED = 'IMPORT_LIST_DATA_VERIFIED';
    case IMPORT_LIST_DATA_NO_INPUT_JAPAN = 'IMPORT_LIST_DATA_NO_INPUT_JAPAN';
    case IMPORT_LIST_DATA_DALAM_PENGAJUAN = 'IMPORT_LIST_DATA_DALAM_PENGAJUAN';
    case IMPORT_LIST_DATA_GENSEN_CAIR = 'IMPORT_LIST_DATA_GENSEN_CAIR';
}
